### ISSUE TITLE
Read instance for SMGen

### ISSUE THREAD

**Issue by nick8325** [phadej/splitmix#13]
It would be handy to have a Read instance to make it easier to use splitmix in QuickCheck (which has a Read instance for `QCGen`).

**Comment by phadej** [comment]
Yes, there are no good reason why instance is omitted. One have to write it by hand to maintain invariant, and I was lazy back then. Will add ASAP. Is there something else missing from `splitmix`, its API is quite barebones, so please tell is some convinience functions can be added

**Comment by nick8325** [comment]
It looks like everything else that QC needs is already there - we mostly just use the basic `System.Random` API.

**Comment by phadej** [comment]
`Read` instance is in https://hackage.haskell.org/package/splitmix-0.0.2

Also there I extended support back to `GHC-7.0` (though then generator is probably quite slow, as I use naive `popCount` then).

**Comment by nick8325** [comment]
Excellent, thanks a lot!
