### ISSUE TITLE
Use Unboxed IORef instead of IORef

### ISSUE THREAD

**Issue by Boarders** [phadej/splitmix#28]
Currently `theSMGen` is defined as:
```haskell
theSMGen :: IORef SMGen
theSMGen = unsafePerformIO $ initSMGen >>= newIORef
{-# NOINLINE theSMGen #-}
```
Which is the same as `random` and various other libraries use to do implicit state. `SMGen` itself is defined as a pair of `Word64`s:
```haskell
data SMGen = SMGen !Word64 !Word64 -- seed and gamma; gamma is odd
```
We can store this in a mutable bytearray and so we might be better off using [unboxed-ref](http://hackage.haskell.org/package/unboxed-ref-0.4.0.0). This in general has better performance as we don't have to chase as many heap pointers and I believe an `IORef` will not be unboxed by GHC. In order to make this change one would need to add a primitive instance to `SMGen` and it would be useful to have some benchmark that checks this is indeed faster.

**Comment by phadej** [comment]
The `theSMGen` is only used to initialize new generators in `newSMGen` which should be rare, non performance critical operation.

Also https://matrix.hackage.haskell.org/#/package/unboxed-ref is not supporting as much GHCs as I'd like, i.e. down from `GHC-7.0`. (I have my reasons to support as old compilers).
