### ISSUE TITLE
Dependency on `random`

### ISSUE THREAD

**Issue by lehins** [phadej/splitmix#34]
@phadej would you be ok removing dependency on random completely? Not right now, of course, but once we get to the final implementation of the new `random`, which is not far at all on the horizon. Reason why I am asking is because we decided it would be best if we just made the `SMGen` the default RNG for `random`, in other words, instead of duplicating splitmix algorithm implementation we went for `type StdGen = SMGen`. This would, of course, require `random` to depend on `splitmix`, not the other way around. We could of course just inline the implementation from your package as mentioned here https://github.com/idontgetoutmuch/random/issues/86, but it really seems like an unnecessary duplication of code.

**Comment by phadej** [comment]
Yes, I'm fine with that. I depend on `random` only to provide `RandomGen` instance, so there aren't any technical problems with that.

**Comment by phadej** [comment]
as you may noted, one can remove `random` dependency already today by supplying `-random` flag choice.

> `random`	 Providen RandomGen SMGen instance Enabled Manual

**Comment by lehins** [comment]
Awesome, thank you!

Yes, that's what we've been using thus far, but if we are to release `random` on hackage that depends on `splitmix` the optional flag approach will no work
> one can remove random dependency already today by supplying -random flag choice.

**Comment by phadej** [comment]
Done in `splitmix-0.1`
