### ISSUE TITLE
mixGamma bug

### ISSUE THREAD

**Issue by Lysxia** [phadej/splitmix#8]
The `mixGamma` function should "fix" its result if the popcount is too low, but in its current version it is doing the opposite.

https://github.com/phadej/splitmix/blob/f6895c4137b14e4752b0575c178199201eb41810/src/System/Random/SplitMix.hs#L141-L144

This is a bug inherited from a typo in the code of the original SplitMix paper. The text gives the correct interpretation:

> Therefore we require that the number of such pairs, as computed by `Long.bitCount(z ^ (z >>> 1))`, exceed `24`; if it does not, then the candidate `z` is replaced by the `XOR` of `z` and `0xaaaaaaaaaaaaaaaaL`

 I found that in this blogpost: http://www.pcg-random.org/posts/bugs-in-splitmix.html

**Comment by phadej** [comment]
Thanks for the report, article seems old, but indeed if I run dieharder with those seeds it makes some test give weak results.

I made a PR to fix this: https://github.com/phadej/splitmix/pull/9 could you @Lysxia look through the code, that I don't have something silly there.

I wonder why the author of article didn't contact me :/

**Comment by phadej** [comment]
This is fixed.
